# Env
device_target: Ascend
save_dir: './runs'
exist_ok: False
device_per_servers: 8
log_level: "INFO"
is_parallel: False
task: 'train'

# Train
ms_strategy: StaticShape
ms_mode: 0
ms_amp_level: O0
ms_loss_scaler: 'static'
ms_loss_scaler_value: 1024.0
ms_grad_sens: 1024.0
ms_jit: True
ms_enable_graph_kernel: False
overflow_still_update: True
clip_grad: False
ema: True
weight: ''
ema_weight: ''
freeze: []
epochs: 300
per_batch_size: 32 # infer 1
img_size: 640
nbs: 64
accumulate: 1
auto_accumulate: True
log_interval: 1
multi_scale: False
single_cls: False
sync_bn: False
keep_checkpoint_max: 10
run_eval: False
rect: False
nms_time_limit: 20.0

# Eval
conf_thres: 0.001
iou_thres: 0.65

# Export
file_format: 'MINDIR' # export
output_path: './' # preprocess
result_path: './result_files' # postprocess

# ModelArts
enable_modelarts: False
data_dir: '/cache/data/'
ckpt_dir: '/cache/pretrain_ckpt/'
data_url: ''
ckpt_url: ''
train_url: ''

---

# Help Env
device_target: 'device target, Ascend/GPU/CPU'
project: 'save to project/name'
name: 'save to project/name'
exist_ok: 'existing project/name ok, do not increment'
device_per_servers: 'device number on a server'
log_level: 'log level, CRITICAL/ERROR/WARNING/INFO/DEBUG'
task: 'train, val, test, export or predict'

# Help Train
ms_strategy: 'train strategy, StaticCell/StaticShape/MultiShape/DynamicShape'
ms_mode: 'Running in GRAPH_MODE(0) or PYNATIVE_MODE(1) (default=0)'
ms_amp_level: 'amp level, O0/O1/O2'
ms_loss_scaler: 'train loss scaler, static/dynamic/none'
ms_loss_scaler_value: 'static loss scale value'
ms_optim_loss_scale: 'optimizer loss scale'
num_parallel_workers: 'num parallel worker for dataloader'
overflow_still_update: 'overflow still update'
is_parallel: 'Distribute train or not'
recompute: 'Recompute'
weight: 'initial weight path'
ema_weight: 'initial ema weight path'
epochs: 'total train epochs'
per_batch_size: 'batch size for per device'
accumulate: 'grad accumulate step, recommended when batch-size is less than 64'
img_size: '[train, test] image sizes'
run_eval: 'Whether to run eval during training'
rect: 'rectangular training'
nms_time_limit: 'time limit for NMS'
multi_scale: 'vary img-size +/- 50%'
single_cls: 'train multi-class data as single-class'
optimizer: 'select optimizer'
sync_bn: 'use SyncBatchNorm, only available in DDP mode'
freeze: 'Freeze layers'

# Help Test
conf_thres: 'object confidence threshold'
iou_thres: 'IOU threshold for NMS'

# Help Infer
file_format: 'Infer-export: treat as single-class dataset'
output_path: 'Infer-preprocess: output preprocess data path'
result_path: 'Infer-postprocess: path to 310 infer result floder'

# Help ModelArts
enable_modelarts: 'ModelArts: enable modelarts'
data_url: 'ModelArts: obs path to dataset folder'
train_url: 'ModelArts: obs path to dataset folder'
data_dir: 'ModelArts: obs path to dataset folder'

---

# Choices Env
device_target: ['Ascend', 'GPU', 'CPU']
log_level: ['CRITICAL', 'ERROR', 'WARNING', 'INFO', 'DEBUG']

# Choices Train
ms_strategy: ['StaticShape', 'DynamicShape']
ms_amp_level: ['O0', 'O1', 'O2', 'O3']
ms_loss_scaler: ['static', 'dynamic']

# Choices Infer
file_format: ['MINDIR', 'AIR']
