__BASE__: [
  '../coco.yaml',
  './hyp.scratch.yaml',
  './yolox-s-2nd.yaml'
]

weight: ./runs/exp_name/weights/yolox-s-285_1848.ckpt
ema_weight: ./runs/exp_name/weights/EMA_yolox-s-285_1848.ckpt

optimizer:
  checkpoint_path: ./runs/exp_name/weights/optim_yolox-s.ckpt

network:
  depth_multiple: 1.33
  width_multiple: 1.25
