__BASE__: [
  '../coco.yaml',
  './hyp.scratch.yaml',
  './yolox-s-2nd.yaml'
]

weight: ./runs/exp_name/weights/yolox-m-285_1848.ckpt
ema_weight: ./runs/exp_name/weights/EMA_yolox-m-285_1848.ckpt

optimizer:
  checkpoint_path: ./runs/exp_name/weights/optim_yolox-m.ckpt

network:
  depth_multiple: 0.67
  width_multiple: 0.75
